name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repositry
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Just
        uses: extractions/setup-just@v2

      - name: Set up Cache
        uses: coursier/cache-action@v6

      - name: Set up Java
        uses: coursier/setup-action@v1
        with:
          jvm: temurin:21

      - name: Check Application's Code Formatting
        run: just check-formatting

      - name: Compile Application
        run: just compile

      - name: Test Application
        run: just test
